### ISSUE TITLE
Review AWS offerings

### ISSUE THREAD

**Issue by jvanulde** [ACWI-SSWD/GSIP#18]
Assess technologies that can be leveraged on AWS.

**Comment by denevers** [comment]
Do you still have the list of technologies you evaluated ?  I remember Blazegraph..

**Comment by jvanulde** [comment]
Blazegraph
Neo4J
Neptune (Blazegraph on AWS)
Dgraph

**Comment by jvanulde** [comment]
https://github.com/NRCan/GSIP/issues/72
